language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
install: true
dist: xenial
script: mvn -V org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar
addons:
  sonarcloud:
    organization: "rombert-github"
    token:
      secure: "CQ5/kyX5QKTF7ZgofdixqZcXufAfmvfjGeMeQCulOG2o2tE7OBFHluoYNTYgNXYviHYJgfq0FrZERDJ6UmzFLv4GsslEVN8fy3tCRH2c5rIkRBqDKpMBvRs3MAAI91hcf8wZWiy5WcFMAvj9TZgC2u5Eb07+HZ2ACFHJoflYSiy9IdevKJSYblVnk+WpCAsEGrZCgidtyugPhn4vEko6c2huYS/4H4Bl4G5UPnsvzbGACbmLI0LYL7f7T07yPP4S2AQzh/pbFQxZieaEaFgiNN5wUAWe/aOEu0CroEY4HXjz66rzOGa2G+/OCVfgI1bgIQZjnmowjnPo/Ys/lH7xsRm4T01ks3A0xcjoNeh6XE5b8nylo37JjwyUmj1MFAMMIFn/dUTUr4aZ75GwM1Ngs6d8x5gIwbFrMbLSVjm1sk1HSqv7Zg9zwrGugqjmxmJEozgIkE4NFErstnSQJ9zgHHV2rcDQNOzgPJ7FP5JJ6wtCvCvuCXLEDAaLeYCfCxYeIV1ARo6E0VZlxlEnZZh9bhAHrXONurrzgdUblgBVjXYTeWQ/nKmNwVyqaVy8ZdvoGM7jG2n/MueM1sPVpq+ihKZsfQML9uGRPMenC6XJt0Wc2O0qtMYckt8ODKPz8/yrzYskFMVmGAEu9ORMbnXKX/UQSsTRoq0vUC4aOZTjqAY=" 
